### ISSUE TITLE
Demo website isn't working

### ISSUE THREAD

**Issue by mbrukman** [mint-lang/mint-realworld#3]
The demo website listed at the top of the repo and in the README — https://realworld.mint-lang.com/ — currently returns an error:

> This site can’t be reached
> realworld.mint-lang.com’s server IP address could not be found.
> DNS_PROBE_FINISHED_NXDOMAIN

**Comment by gdotdesign** [comment]
I've fixed the DNS settings, thanks for letting me know. It needs some time to propagate until then you can reach the demo from here: https://mint-realworld.netlify.com/
