### ISSUE TITLE
Can't build with mint 0.7.1 (external-javascripts)

### ISSUE THREAD

**Issue by johanbrandhorst** [mint-lang/mint-realworld#6]
I get the following error when running `mint build`, `install` or `start`:
```
$ mint version
Mint - Showing version
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Mint 0.7.1
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
All done in 111μs!
$ mint install
Mint - Installing dependencies
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

░ MINT.JSON ERROR ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

The root object of a mint.json file has an invalid key: external-javascripts 

Here is the relevant code snippet: 

┌──┬ /<REDACTED>/mint-realworld/mint.json ───────────────────────┐
│ 5│   ],                                                                      │
│ 6│   "test-directories": [                                                   │
│ 7│     "tests"                                                               │
│ 8│   ],                                                                      │
│ 9│   "external-javascripts": [                                               │
│10│     "assets/commonmark.js"                                                │
│11│   ],                                                                      │
│12│   "application": {                                                        │
│13│     "name": "Conduit",                                                    │
└──┴───────────────────────────────────────────────────────────────────────────┘

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
There was an error exiting...
```

Was this configuration variable deprecated silently? I couldn't find anything in the [release notes](https://github.com/mint-lang/mint/releases) about it.

**Comment by s0kil** [comment]
Will be fixed with https://github.com/mint-lang/mint-realworld/pull/5

**Comment by johanbrandhorst** [comment]
You are on :fire: today Daniel! Thanks! I think the deprecation should be added to the release notes too. Do you have the power to make that change or should I raise an issue?

**Comment by s0kil** [comment]
This issue does or should not affect the latest release (`0.7.1`).
Did you build `mint` from source?

**Comment by s0kil** [comment]
I'm not sure if the binary in https://www.mint-lang.com/install is the latest stable release (https://github.com/mint-lang/mint/releases) or it's the latest binary built from the master branch.

**Comment by johanbrandhorst** [comment]
I installed mint from the downloads page on the official website. The mint binary seems to think it's version 0.7.1 (see top of snippet in issue).

**Comment by gdotdesign** [comment]
Sorry about this, the binary on the install page points to the build from master branch, which caused this issue. 

I'll try to fix it over the weekend and release a new version as well.

**Comment by johanbrandhorst** [comment]
> Sorry about this, the binary on the install page points to the build from master branch, which caused this issue.
> 
> I'll try to fix it over the weekend and release a new version as well.

Thanks! There's another bug then; `mint version` seems incorrect in the latest build. I guess it's some sort of build time variable?

**Comment by gdotdesign** [comment]
Yes it is a build time variable and it comes from the `shard.yml` so I'm not sure it's a bug or how to resolve it without bumping the version in master.

**Comment by johanbrandhorst** [comment]
I think we should definitely consider it a bug that the `mint` binary thinks it's using `0.7.1` when it's not built from the tag `0.7.1`. The common practice here is to change the version to something like `0.8.0-devel` as soon as you tag a release. See https://github.com/grpc/grpc-go/commit/ca10cab155cfd48ea43af22dea669df2606d2d4e.

**Comment by gdotdesign** [comment]
It a good practice, I think I'll use it :+1:

**Comment by gdotdesign** [comment]
I've updated the repo so it works with 0.8.0 :rocket:
